### ISSUE TITLE
Integration with Solis via TCP modbus ?

### ISSUE THREAD

**Issue by rosenightingale** [Moondevil-ha/solis-smart-charging#1]
Do you think this automation might be adapted to work through TCP modbus to solis inverters, in addition to via solis cloud, please?

**Comment by Moondevil-ha** [comment]
I don't see any reason why not. The part where the Soliscloud api is called would simply need to be changed to use the modbus codes. Unfortunately I do not have access to any kit to test this, but I'll look at the theory.

**Comment by Moondevil-ha** [comment]
Can you confirm if you're already use a modbus integration, and which one it is? I can then look at retrofitting the code to match that implementation?

**Comment by rosenightingale** [comment]
Yes, thank you so much. I use Solis Modbus. https://solis-modbus.readthedocs.io/en/latest/

**Comment by Moondevil-ha** [comment]
OK, there's a new file there called solis_modbus_smart_charging.py. Give it a go with the automation below (change the octopus intelligent sensor to match your account code:

alias: Sync Solis Charging with Octopus Dispatch
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.octopus_energy_a_42185595_intelligent_dispatching
    attribute: planned_dispatches
conditions:
  - condition: template
    value_template: >
      {% set dispatches =
      state_attr('binary_sensor.octopus_energy_a_42185595_intelligent_dispatching',
      'planned_dispatches') %} {% if dispatches is none %}
        {% set result = false %}
      {% else %}
        {% set result = true %}
      {% endif %} {{ result }}
actions:
  - action: pyscript.solis_modbus_smart_charging
    metadata: {}
    data:
      config: |-
        {
          "switch_prefix": "switch.solis",
          "number_prefix": "number.solis",
          "dispatch_sensor": "binary_sensor.octopus_energy_a_42185595_intelligent_dispatching"
        }
mode: single


As noted, I can't test this, but if you have the cards you should be able to see if it works? I've been using an AI to perform and check the coding so YMMV.

**Comment by rosenightingale** [comment]
Many thanks indeed, very grateful for your help. As I'm quite new to HA, I'm just following steps quite slowly. I've got pyscript on and added your code into file editor with a new file. Just doing the automations, editing in YAML, I've got this  (with my account number in) but when I save, I get Error in parsing YAML: missed comma between flow collection entries (line: 6, column: 14). I hope I've copied it in correctly, but please do let me know if I've made a rookie error here. As soon as this is correct, I'll be able to test this out today with car charging and report back!. 
![image](https://github.com/user-attachments/assets/9bf8bce8-8168-4861-8355-152e3198a91a)

**Comment by Moondevil-ha** [comment]
Apologies, my text above needs indenting properly to work. YAML needs spacing and commas in the exact places. It should look like this:
![image](https://github.com/user-attachments/assets/7d00b0a8-71c9-4a97-8cf6-6d73bc2edd44)

**Comment by rosenightingale** [comment]
Oh that makes complete sense, thank you. Ok, it has now saved correctly without telling me there are errors etc. So, I shall in a car to charge later on and see what happens. Will let you know when there are any results for this. Many thanks indeed. This looks incredibly useful for people with solis batteries.

**Comment by rosenightingale** [comment]
Ran a car charge overnight which took place 2.30am until 7.30am, so including 2 hours outside the usual set window where inverter is set to charge from grid anyway. Unfortunately the batteries didn't charge in the extra slots although after waiting for 20 minutes I set them to do so manually to take advantage of the additional 7p tariff. 
Is there something in the solis settings perhaps which is blocking it? If there's anywhere I can look to diagnose this or if you have any insights, I'd be grateful.

**Comment by Moondevil-ha** [comment]
What we#ll need is the output from the logs around the time the
script should have kicked off. You can get these from the
Settings/Logs/View complete log. Scroll until you find the time stamps (or
use the search for solis_modbus). The logging is pretty comprehensive. If
you paste (or attach as a text file) the logs for that period I'll take a
look.

**Comment by Moondevil-ha** [comment]
Firstly though, make sure you've followed the instructions. The automation above has got *my* account number in the dispatch sensor. you need to ensure all the entities are changed to match your system. You can see if the automation ran by look at the automation page.

**Comment by rosenightingale** [comment]
Thank you, does this help? 

![image](https://github.com/user-attachments/assets/f4cc2666-a8cd-43ea-bca9-e020a7875ade)

**Comment by rosenightingale** [comment]
Yes, I did change the octopus account number, so I don't think it's that. On the automations page, it says it was never triggered, which would explain things!

**Comment by Moondevil-ha** [comment]
It does, it doesn't look like the script triggered (it should trigger when the dispatches get sent, which is when you plug the car in). Can you check my suggestion above about the entities in the automation?

**Comment by rosenightingale** [comment]
You're right, when I drilled into the details in automation, it looks like the wrong account number in there, I'm so sorry, I thought I'd changed it where it occurred, must have missed one. Will go back and re-check. 

![image](https://github.com/user-attachments/assets/de991bea-3f2d-49e1-9d56-a3b83181fc92)

**Comment by rosenightingale** [comment]
I'm so sorry, you're quite right, it looks as if I missed changing the account number somewhere. I thougth I'd done them all, this is what shows when I drill down into the automation. I need to go back and recheck and make sure I've changed the account number everywhere. 
![image](https://github.com/user-attachments/assets/538ec300-6275-48a8-9e47-eaf56e59702d)

**Comment by Moondevil-ha** [comment]
So once you've changed this, you can test it manually. 

1. Remove all the charge windows from the inverter
2. Manually trigger the automation (right click and run)
3. As there are no dispatches, the script should set the charge windows to 23:30 - 05:30 and populate the local sensors.

**Comment by rosenightingale** [comment]
I'm afraid no luck with that. I must still have something wrong. 
![image](https://github.com/user-attachments/assets/08c49eb3-7d1b-4596-83e3-834ec3e64ed5)

**Comment by Moondevil-ha** [comment]
Once you've changed the account number throughout the automation, we need
to look at why the error is "pyscript...." not found.

It looks like the service isn't registered, so we need to check the
location of the script, and ensure that you're calling the correct name in
the automation.

You can check to see how the script is registered by going to the actions
tab in developer tools and starting to type pyscript. That should list
every pyscript service that is registered, like the below:
[image: image.png]

**Comment by rosenightingale** [comment]
![image](https://github.com/user-attachments/assets/2a3a2475-51fd-4ee5-a8bb-ba13cb6b5d2d)

**Comment by rosenightingale** [comment]
![image](https://github.com/user-attachments/assets/c94a9aa4-487b-47b7-91f1-0f9537392d2d)

**Comment by Moondevil-ha** [comment]
OK, so the service is not registered. This can be caused by the script
being in the wrong place, or by a type/spacing error in the script. First,
check that the script is in the correct place. It should be in
config/pyscript directory.

Next, check the script has been pasted correctly. I find it easiest to use
the Studio Code server add-on :
[image: image.png]

This will highlight any errors in spacing in the code, as it
understands how python etc need to be formatted.

**Comment by rosenightingale** [comment]
You're right, in the File Editor, pyscript directory, it just says Bad Gateway. 
Also, in Devices, the Pyscript says there are no devices or entities. 
![image](https://github.com/user-attachments/assets/fea4d2d8-7aa2-4af8-b17c-c8881276f429)

**Comment by Moondevil-ha** [comment]
It would be helpful to understand where you put the script initially, and
how you pasted it there.

I apologise if this is a bit "blind leading the blind" but I'm only
familiar with my own environment.

This is the contents of my /config/pyscript directory.
[image: image.png]
If you don't have this directory, you probably need to create it, and put
the script in there.

**Comment by rosenightingale** [comment]
Please don't apologies, you're being so incredibly helpful and a lot of this is new to me. I had downloaded Pyscript from HACS, rather than installed it in file editor. Would you recommend I remove it and start again, perhaps with a manual install? I can try to do that. Thank you for persevering here, it would be wonderful if it worked.

**Comment by Moondevil-ha** [comment]
I think pyscript is fine, you just need the file in the correct directory.Home assistant is built on Linux, and has a Unix based file system. You’ll need to create the pyscript directory under ../config to get this to work. If you browse saving locations in your text editor, I assume that pyscript is not already there under config?Bob HardingTel: 07368857815On 8 Dec 2024, at 10:02, rosenightingale ***@***.***> wrote:﻿
Please don't apologies, you're being so incredibly helpful and a lot of this is new to me. I had downloaded Pyscript from HACS, rather than installed it in file editor. Would you recommend I remove it and start again, perhaps with a manual install? I can try to do that. Thank you for persevering here, it would be wonderful if it worked.

**Comment by Moondevil-ha** [comment]
Closed, solis_modbus now working and will be moved to it's own project,
